In [201]:
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import numpy as np
pd.options.display.max_rows = 999
pd.options.display.max_columns = 50

In [173]:
df = pd.read_csv('Glassdoor_Jobs_19-Mar-2021.csv', sep="\t")

In [174]:
df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Compensation_and_Benefits,Culture_and_Values,Career_Opportunities,Work_Life_Balance
0,0,Principal Data Scientist,$108K - $144K (Glassdoor est.),"Working out of our Chevy Chase, MD/Washington ...",3.5,GEICO\n3.5,"Chevy Chase, MD",10000+ Employees,1936.0,Subsidiary or Business Segment,Insurance Carriers,Insurance,$10+ billion (USD),4.0,3.5,3.8,3.1
1,1,Data Scientist,$108K - $144K (Glassdoor est.),"Secure our Nation, Ignite your Future\nOvervie...",3.5,ManTech International Corporation\n4.3,"Alexandria, VA",5001 to 10000 Employees,1968.0,Company - Public,Research & Development,Business Services,$1 to $2 billion (USD),4.2,4.2,4.2,4.2
2,2,"Data Scientist, LiveRamp Safe Haven",$108K - $144K (Glassdoor est.),"Data Scientist, LiveRamp Safe Haven\nLiveRamp ...",3.5,LiveRamp\n4.3,"San Francisco, CA",1001 to 5000 Employees,2005.0,Company - Public,Computer Hardware & Software,Information Technology,$100 to $500 million (USD),4.5,4.4,4.4,4.4
3,3,Senior Data Scientist,$108K - $144K (Glassdoor est.),"Working out of our Chevy Chase, MD/Washington ...",3.5,GEICO\n3.5,"Chevy Chase, MD",10000+ Employees,1936.0,Subsidiary or Business Segment,Insurance Carriers,Insurance,$10+ billion (USD),4.0,3.5,3.8,3.1
4,4,R&D Scientist I,$108K - $144K (Glassdoor est.),"23 Mill Brook Road\nSaco, Maine 04072\nFax: 20...",3.5,"Maine Molecular Quality Controls, Inc\n1.0","Saco, ME",1 to 50 Employees,-1.0,Company - Private,-1,-1,$1 to $5 million (USD),1.0,1.0,3.0,2.3

In [175]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue',
       'Compensation_and_Benefits', 'Culture_and_Values',
       'Career_Opportunities', 'Work_Life_Balance'],
      dtype='object')

In [176]:
def title_simplifier(title):
    if 'data scientist' in title.lower():
        return 'data scientist'
    elif 'data engineer' in title.lower():
        return 'data engineer'
    elif 'analyst' in title.lower():
        return 'analyst'
    elif 'machine learning' in title.lower():
        return 'mle'
    elif 'manager' in title.lower():
        return 'manager'
    elif 'director' in title.lower():
        return 'director'
    else:
        return 'na'
    
def seniority(title):
    if 'sr' in title.lower() or 'senior' in title.lower() or 'sr' in title.lower() or 'lead' in title.lower() or 'principal' in title.lower():
            return 'senior'
    elif 'jr' in title.lower() or 'jr.' in title.lower():
        return 'jr'
    else:
        return 'na'

In [177]:
#Limpio el target, no puede contener na
df = df.dropna(subset=['Salary Estimate'])
df['Salary Estimate'].head()

0    $108K - $144K (Glassdoor est.)
1    $108K - $144K (Glassdoor est.)
2    $108K - $144K (Glassdoor est.)
3    $108K - $144K (Glassdoor est.)
4    $108K - $144K (Glassdoor est.)
Name: Salary Estimate, dtype: object

In [178]:
df['job_simp'] = df['Job Title'].apply(title_simplifier)

In [179]:
df.job_simp.value_counts()

data scientist    253
na                117
analyst            61
data engineer      47
manager            16
mle                13
director            1
Name: job_simp, dtype: int64

In [180]:
df['seniority'] = df['Job Title'].apply(seniority)
df.seniority.value_counts()

na        420
senior     88
Name: seniority, dtype: int64

In [181]:
df['Location'].value_counts()

San Francisco, CA                    20
New York, NY                         16
Chicago, IL                          15
Boston, MA                           14
Washington, DC                       14
Remote                               13
Cambridge, MA                        12
San Diego, CA                        10
Seattle, WA                           9
Arlington, VA                         9
San Jose, CA                          7
United States                         7
Palo Alto, CA                         7
Baltimore, MD                         6
Princeton, NJ                         6
Austin, TX                            6
Saint Louis, MO                       6
Charlotte, NC                         5
Rockville, MD                         5
Minneapolis, MN                       4
Menlo Park, CA                        4
Culver City, CA                       4
Ipswich, MA                           4
Laurel, MD                            4
Chantilly, VA                         4
Fort Meade, MD                        4
Chevy Chase, MD                       4
Houston, TX                           4
Mountain View, CA                     4
Philadelphia, PA                      4
Gaithersburg, MD                      4
Springfield, VA                       3
Madison, WI                           3
American Fork, UT                     3
Newark, DE                            3
Fort Wayne, IN                        3
Durham, NC                            3
Portsmouth, VA                        3
Emeryville, CA                        3
Colorado Springs, CO                  3
Harrisburg, PA                        3
Saint Petersburg, FL                  3
Wilmington, DE                        3
Cincinnati, OH                        3
Aliso Viejo, CA                       3
San Mateo, CA                         3
Redwood City, CA                      3
Stamford, CT                          3
Exton, PA                             3
Albuquerque, NM                       3
Indianapolis, IN                      3
Los Angeles, CA                       3
Memphis, TN                           3
Duarte, CA                            3
Dallas, TX                            3
McLean, VA                            3
Salt Lake City, UT                    3
Milwaukee, WI                         3
Atlanta, GA                           3
Bedminster, NJ                        2
Sunnyvale, CA                         2
Denver, CO                            2
San Antonio, TX                       2
Columbia, MD                          2
Alexandria, VA                        2
Natick, MA                            2
Irvine, CA                            2
Oakdale, CA                           2
Rosemont, IL                          2
Somerville, MA                        2
Santa Clara, CA                       2
Arlington, TX                         2
Long Beach, CA                        2
Worcester, MA                         2
Wichita, KS                           2
Kentucky                              2
Draper, UT                            2
Kansas City, MO                       2
Miami Lakes, FL                       2
Carlsbad, CA                          2
Pittsburgh, PA                        2
King of Prussia, PA                   2
Santa Monica, CA                      2
Phoenix, AZ                           2
Reston, VA                            2
Ottsville, PA                         2
Pensacola, FL                         2
California                            2
Saco, ME                              2
Monrovia, CA                          2
Overland Park, KS                     2
Camden, NJ                            2
Nashua, NH                            2
Brea, CA                              2
Tysons Corner, VA                     2
Richmond, VA                          2
Raleigh, NC                           2
Bethesda, MD                          1
Missoula, MT                          1
Midland Park, NJ                      1
Glendale, CA                          1
Grand Island, NY                      1
Oklahoma City, OK                     1
Chandler, AZ                          1
Hampton, VA                           1
Hoffman Estates, IL                   1
Foster City, CA                       1
Lexington-Fayette, KY                 1
Middleton, WI                         1
Greenville, SC                        1
Temple City, CA                       1
Liverpool, NY                         1
Blacksburg, VA                        1
Louisville, KY                        1
Ewing, NJ                             1
Iola, KS                              1
Severna Park, MD                      1
San Carlos, CA                        1
Gallatin, TN                          1
Fort Washington, PA                   1
Providence, RI                        1
Wellesley, MA                         1
Morrisville, NC                       1
Juncos, PR                            1
Levittown, PA                         1
Research Triangle Park, NC            1
Colorado                              1
Lehi, UT                              1
Knoxville, TN                         1
Wilmington, NC                        1
Westlake Village, Los Angeles, CA     1
Lynnwood, WA                          1
Dublin, OH                            1
La Jolla, CA                          1
Cranberry Township, PA                1
San Bernardino, CA                    1
Asheville, NC                         1
South Dennis, MA                      1
South Jordan, UT                      1
Topeka, KS                            1
Silver Spring, MD                     1
Detroit, MI                           1
Greensboro, NC                        1
Ankeny, IA                            1
Evansville, IN                        1
Tewksbury, MA                         1
Conshohocken, PA                      1
Redmond, WA                           1
Van Wert, OH                          1
Brookhaven, NY                        1
Falls Church, VA                      1
Framingham, MA                        1
Medford, OR                           1
Buffalo, NY                           1
Niagara Falls, NY                     1
Chesterfield, MO                      1
Edgewater Park, NJ                    1
Kansas City, KS                       1
Glen Allen, VA                        1
Lexington, MA                         1
Olathe, KS                            1
Fremont, CA                           1
Boulder, CO                           1
Spring, TX                            1
Burlingame, CA                        1
Carson, CA                            1
Santa Barbara, CA                     1
Charleston, WV                        1
Hanover, MD                           1
Traverse City, MI                     1
Columbus, OH                          1
Groton, CT                            1
Pleasanton, CA                        1
Alachua, FL                           1
Half Moon Bay, CA                     1
Wilson, NC                            1
Nashville, TN                         1
Riviera Beach, FL                     1
South San Francisco, CA               1
Smithfield, VA                        1
Golden Valley, MN                     1
Moline, IL                            1
Orlando, FL                           1
Farmington, CT                        1
Ann Arbor, MI                         1
Cary, NC                              1
Bethlehem, PA                         1
Beverly Hills, CA                     1
Herndon, VA                           1
West Palm Beach, FL                   1
Camarillo, CA                         1
Plainsboro, NJ                        1
Jersey City, NJ                       1
Ogden, UT                             1
Waltham, MA                           1
Portland, OR                          1
Mooresville, NC                       1
Livonia, MI                           1
Newburyport, MA                       1
Beavercreek, OH                       1
Omaha, NE                             1
Duluth, GA                            1
Grand Rapids, MI                      1
Plymouth, IN                          1
Chesterbrook, PA                      1
Coralville, IA                        1
New Jersey                            1
Westborough, MA                       1
Attleboro, MA                         1
Dayton, OH                            1
Name: Location, dtype: int64

In [182]:
#Reemplazo los estados que no tenian sigla manualmente
df['Location']= df.Location.apply(lambda x: 'na' if 'United States' in x else x)
df['Location']= df.Location.apply(lambda x: 'CA' if 'California' in x else x)
df['Location']= df.Location.apply(lambda x: 'CO' if 'Colorado' in x else x)
df['Location']= df.Location.apply(lambda x: 'KT' if 'Kentucky' in x else x)
df['Location']= df.Location.apply(lambda x: 'NJ' if 'New Jersey' in x else x)
df['job_state'] = df['Location'].apply(lambda x:x.strip().split(',')[1][1:] if ',' in x else x) #Divido, tomo el segundo elemento, y desde el segundo caracter porque el primero es el espacio despues de la coma
df['job_state'] = df['job_state'].apply(lambda x: x if x.strip().lower() != 'los angeles' else 'CA') #Corrijo los angeles
df['job_state'].value_counts()

CA        110
MA         45
VA         36
MD         33
PA         22
NY         21
IL         19
NC         18
TX         18
NJ         16
DC         14
Remote     13
WA         11
UT         11
FL         11
MO          9
OH          8
IN          8
KS          8
CO          7
na          7
WI          7
TN          6
DE          6
MI          5
MN          5
CT          5
GA          4
NM          3
AZ          3
KY          2
ME          2
NH          2
IA          2
KT          2
OR          2
SC          1
PR          1
OK          1
WV          1
MT          1
NE          1
RI          1
Name: job_state, dtype: int64

In [183]:
#  Job description length 
df['desc_len'] = df['Job Description'].apply(lambda x: len(x))
df['desc_len'].head()

0    5214
1    7027
2    8065
3    4691
4    4864
Name: desc_len, dtype: int64

In [184]:
#Parsing Salary
salary = df['Salary Estimate'].apply(lambda x: x.split('(')[0])
minus_Kd = salary.apply(lambda x: x.replace('K','').replace('$',''))

In [185]:
#calculo minimo y maximos
df['min_salary'] = minus_Kd.apply(lambda x: int(x.split('-')[0]))
df['max_salary'] = minus_Kd.apply(lambda x: int(x.split('-')[1]))

In [186]:
#Salario promedio estimado
df['avg_salary'] = (df.min_salary+df.max_salary)/2

In [187]:
#Obtengo nombre compania
df['company_txt'] = df.apply(lambda x: x['Company Name'] if x['Rating'] <0 else x['Company Name'][:-3], axis = 1).replace('\n','',regex=True)

In [188]:
df['company_txt'].head()

0                                    GEICO
1        ManTech International Corporation
2                                 LiveRamp
3                                    GEICO
4    Maine Molecular Quality Controls, Inc
Name: company_txt, dtype: object

In [194]:
#Age of the company, assuming that companies that doesnt have found date, are new.
df['age'] = df.Founded.apply(lambda x: 1 if x ==-1.0 else 2020 - x)

In [195]:
df['age'].head()

0    84.0
1    52.0
2    15.0
3    84.0
4     1.0
Name: age, dtype: float64

In [196]:
#parsing of job description (python, etc.)

#python
df['python_yn'] = df['Job Description'].apply(lambda x: 1 if 'python' in x.lower() else 0)
 
#r studio 
df['R_yn'] = df['Job Description'].apply(lambda x: 1 if 'r studio' in x.lower() or 'r-studio' in x.lower() else 0)
df.R_yn.value_counts()

#spark 
df['spark'] = df['Job Description'].apply(lambda x: 1 if 'spark' in x.lower() else 0)
df.spark.value_counts()

#aws 
df['aws'] = df['Job Description'].apply(lambda x: 1 if 'aws' in x.lower() else 0)
df.aws.value_counts()

#excel
df['excel'] = df['Job Description'].apply(lambda x: 1 if 'excel' in x.lower() else 0)
df.excel.value_counts()

1    258
0    250
Name: excel, dtype: int64

In [197]:
df.columns

Index(['Unnamed: 0', 'Job Title', 'Salary Estimate', 'Job Description',
       'Rating', 'Company Name', 'Location', 'Size', 'Founded',
       'Type of ownership', 'Industry', 'Sector', 'Revenue',
       'Compensation_and_Benefits', 'Culture_and_Values',
       'Career_Opportunities', 'Work_Life_Balance', 'job_simp', 'seniority',
       'job_state', 'desc_len', 'min_salary', 'max_salary', 'avg_salary',
       'company_txt', 'age', 'python_yn', 'R_yn', 'spark', 'aws', 'excel'],
      dtype='object')

In [203]:
df_out = df.drop(['Unnamed: 0'], axis =1)
df_out

                                             Job Title  \
0                             Principal Data Scientist
1                                       Data Scientist
2                  Data Scientist, LiveRamp Safe Haven
3                                Senior Data Scientist
4                                      R&D Scientist I
5                        Product Development Scientist
6                                    Lead Data Analyst
7                Data Engineering Technical Supervisor
8                              Spark/Big Data Engineer
9                             Senior Bioinfo Scientist
10                 Sr Scientist, Molecular Engineering
11                                       R&D Scientist
12              Staff Scientist II - Molecular Biology
13                                  Sr. Data Scientist
14                                      Data Scientist
15                   Research Scientist - Gene therapy
16                                 ASSOCIATE SCIENTIST
17                     Lead, Machine Learning Engineer
18                     Research Scientist I - Essentia
19                                      Data Scientist
20                                           Scientist
21                                 Principal Scientist
22                                 Lead Data Scientist
23                                      MS&T Scientist
24                           HR Systems & Data Analyst
25                                Data Science Manager
26                                  In Vitro Scientist
27                                        Data Analyst
28                                       Data Engineer
29                                 ASSISTANT SCIENTIST
30                                Data Scientist - HCI
31                               Senior Data Scientist
32                                Staff Data Scientist
33                         Assay Development Scientist
34                               Senior Data Scientist
35   Sr. Validation Scientist 30557- Process Valida...
36                                      Data Scientist
37                 Data Scientist - Customer Marketing
38                            Clinical Lab Scientist l
39     Staff Scientist II - Cell and Molecular Biology
40                                        Data Analyst
41                                      Data Scientist
42   Experienced Lumber & Building Materials Data A...
43                        Data Visualization Scientist
44                                        Data Analyst
45                              Microbiology Scientist
46                                   Analytics Manager
47                     Research Scientist - Immunology
48                             Medical Lab Scientist I
49                              Staff/Senior Scientist
50                        Data Science Project Manager
51                                  Research Scientist
52                       Clinical Laboratory Scientist
53            Senior Data Scientist (Machine Learning)
54   Scientist/Sr Scientist, Immunology/Cancer Immu...
55                         Data & Analytics Consultant
56   (FOOD SCIENTIST) Sr. Product Development Techn...
57                            Sr Scientist- Downstream
58                                        Data Analyst
59                                           Scientist
60                                      Data Scientist
61                     Data Scientist - ETL Pipelining
62               Clinical Research Molecular Scientist
63                Pricing Strategy & Analytics Manager
64                                    R&D Scientist II
65                            Scientist, Tech Transfer
66                             Research Data Scientist
67                      SCIENTIST - BIOPHARMACEUTICALS
68                            Principal Data Scientist
69                           Core Measure Data Analyst
70                                   Data Engineer III
71             Scientist/Junior Faculty: Tumor Biology
72                                        Data Analyst
73                                      Data Scientist
74                               Scientist, Biomarkers
75                           Machine Learning Engineer
76                                 Data Science Intern
77         Scientist Nanoparticle Platform Development
78                                 Health Data Analyst
79              Scientist Upstream Process Development
80             Environmental Scientist Project Manager
81           Scientist/Sr. Scientist Peptide Chemistry
82                                       Data Engineer
83                 Data Engineer / Care Transformation
84                                      Data Scientist
85                                      Data Scientist
86                     High-Throughput Assay Scientist
87                                       Data Engineer
88                                   SCIENTIST - LC-MS
89           Scientist, Downstream Process Development
90                      Senior Data Scientist (MS2266)
91                                      Data Scientist
92                                      Data Scientist
93   Acoustic Signal Processing Engineer - Data Sci...
94                                        Data Analyst
95                                      Data Scientist
96                          Bioinformatics Scientist I
97               Scientist - Biology and Biostatistics
98   Associate Scientist/Senior Associate Scientist...
99   Scientist/Senior Scientist - X-ray Crystallogr...
100                              Treasury Data Analyst
101  Lead Analytics Data Engineer (Remote) - Data S...
102                                      Data Engineer
103                       Engineer - Data Engineer III
104      Bioinformatics Scientist, Research Department
105            Technology Transfer Scientist Level III
106                         Operational Data Scientist
107                                 Decision Scientist
108                                     Data Scientist
109                              Intern - Data Science
110                                     LEAD SCIENTIST
111          Immune Cell Therapy PhD Scientist Faculty
112                          Quantitative Data Analyst
113                                LEAD DATA SCIENTIST
114                              Senior Data Scientist
115                       Medical Laboratory Scientist
116                              Senior Data Scientist
117                      Business Intelligence Analyst
118                                      Data Engineer
119                          Medical Lab Scientist MLS
120                                Lead Data Scientist
121  Arity-Senior Data Scientist - Machine Learning...
122                      Business Intelligence Analyst
123                              Senior Data Scientist
124                   Marketing Data Analytics Manager
125            Senior Analytics Data Engineer (Remote)
126                      Business Intelligence Analyst
127                               Data Scientist - HCI
128                                     Data Scientist
129  Medical Laboratory Scientist/Technologist (MLS...
130                                       Data Analyst
131          Business Analyst - Claim and Data Analyst
132                        Research Scientist or Above
133                         Research Scientist - Radar
134             Data Analyst - Digital Ad Intelligence
135            Data Scientist - Defense & Intelligence
136  Product Strategy Leader - Data Science Technol...
137                      Business Intelligence Analyst
138                      Business Intelligence Analyst
139                              Senior Data Scientist
140                                     Data Scientist
141                HIM SYSTEM DATA ANALYST - Part-Time
142                                ETL QA/Data Analyst
143         Scientist III, Quality Control - 2nd Shift
144                              Senior Data Scientist
145  Associate/Sr. Associate Scientist Peptide Chem...
146                      Business Intelligence Analyst
147  Scientist - Stem Cells, Neuroscience, Biomater...
148                                       Data Modeler
149                              Energy Data Scientist
150                                     Data Scientist
151     Data Scientist, Analytics - Messaging Platform
152                          Supply Chain Data Analyst
153                      Clinical Laboratory Scientist
154                             Lead Wetland Scientist
155                               Senior Data Engineer
156                                     Data Scientist
157               Data Scientist, Revenue Optimization
158                             Scientist - Analytical
159                           Interchange Data Analyst
160                                Scientist - cryo EM
161                                      Data Engineer
162                                   CRA Data Analyst
163                      Data Scientist - Intermediate
164  Medical Lab Scientist Full Time Day Saint Luke...
165                Intern - Data Science (Summer 2021)
166                                       Data Analyst
167                                  Analytics Manager
168                       Vaccine Production Scientist
169           Sr. Scientist, Bioreactor Process Design
170                     Staff/Principal Data Scientist
171                                      Data Engineer
172                     Provider Data Analyst - REMOTE
173                           Data Scientist -- Senior
174                                       Data Analyst
175                                     Data Scientist
176                                  Sr Data Scientist
177              Digital Engagement Data Analyst/Admin
178                Data Scientist Technical Specialist
179                                     Data Scientist
180            AI/ML Health Data Scientist- Consultant
181                           Data Scientist - W2 Only
182  Data Scientist - (P&C Insurance Experience Req...
183                                     Data Scientist
184                             THz Research Scientist
185  Housing Counselling & Financial Services Data ...
186                            Manufacturing Scientist
187                   Data Scientist with TS Clearance
188                                       Data Analyst
189                                     Data Architect
190                     Program Finance & Data Analyst
191           Principal Scientist, Analytical Research
192                                Market Data Analyst
193                                     Data Scientist
194                                      Data Engineer
195                                     Data Scientist
196                              Data Scientist-Junior
197                                     Data Scientist
198                               Data Science Manager
199                Business Intelligence Data Engineer
200                Data Scientist, Medical Diagnostics
201                                     Data Scientist
202     Supply Chain Data Analyst (South of Milwaukee)
203   Clinical Laboratory Scientist, Molecular (CGMBS)
204                                     Data Scientist
205                            Healthcare Data Analyst
206                             Data Analyst/Developer
207                   Data Engineer (Machine Learning)
208                                     Data Scientist
209                                     Data Scientist
210                      Sr. Consultant Data Scientist
211                      Sr. Consultant Data Scientist
212                                      Data Engineer
213                Data Scientist/Analytics Specialist
214                    Business Analyst - Data Science
215                           AOD Data Science Advisor
216                     Lead Data Scientist / Engineer
217  Senior Data Scientist/Machine Learning Softwar...
218                                     Data Scientist
219                            Data Analyst (Power BI)
220                 Product Development Lead Scientist
221       Attending Veterinarian / Principal Scientist
222                                     Data Scientist
223                   UAV Propulsion Modeling Engineer
224                              Senior Data Scientist
225                                     Data Scientist
226                           Scientist - life science
227                                     Data Scientist
228                    Data Scientist - ETL Pipelining
229                              Contract Data Analyst
230                            Principal Data Engineer
231                                     Data Scientist
232                          Machine Learning Engineer
233             Marketing Analytics Manager, eCommerce
234   Corporate Analytics Manager (South of Milwaukee)
235                                     Data Scientist
236                       Flight Control Data Engineer
237     Senior Data Scientist - Defense & Intelligence
238                                      Data Engineer
239                   Scientist / Sr. Scientist - HPLC
240                              Senior Data Scientist
241             Lead Data Scientist, Product Analytics
242  Medical Lab Scientist Full Time Day Saint Luke...
243                            Healthcare Data Analyst
244        SCIENTIST - POTENCY BIOASSAY , ELISA , FACS
245                                      Data Engineer
246                   Data Engineer (Machine Learning)
247               Clinical Lab Scientist l (Full-Time)
248                                     Data Scientist
249                                     Data Scientist
250                Data Scientist/Analytics Specialist
251            SCIENTIST - DEVICE QC , FTIR , DSC, GMP
252                    Business Analyst - Data Science
253                           AOD Data Science Advisor
254                     Scientist, Compound Management
255                                      Data Engineer
256  Research Scientist/Senior Research Scientist A...
257                             Data Analyst/Developer
258                     Lead Data Scientist / Engineer
259                                     Data Scientist
260                             Cloud BI/Data Engineer
261                                      Data Engineer
262  Senior Data Scientist/Machine Learning Softwar...
263                            Data Analyst (Power BI)
264                                Data Science Intern
265                 Product Development Lead Scientist
266       Analytical Method Validation (AMV) Scientist
267                                     Data Scientist
268       Attending Veterinarian / Principal Scientist
269                                     Data Scientist
270  Clinical Laboratory Scientist CLS , Medical Da...
271                  Supply Chain Analytics Consultant
272                                Data Science Intern
273                                  Data Scientist II
274                    Data Scientist - ETL Pipelining
275                                       Data Analyst
276              Scientist, QC Cell Assay - Relocation
277                            Principal Data Engineer
278                Supply Chain Data Analytics Manager
279                     Lead Data Scientist / Engineer
280                                     Data Scientist
281                              Contract Data Analyst
282                          Machine Learning Engineer
283                               Digital Data Analyst
284            Certifying Scientist (2nd or 3rd Shift)
285       Scientist, Analytical Research & Development
286             Marketing Analytics Manager, eCommerce
287                                     Data Scientist
288                Data Analyst - Potential for Remote
289           Business Intelligence Analyst, Marketing
290                  Data Scientist, Product Analytics
291              Environmental Scientist/Field Manager
292                      Senior Revenue Data Scientist
293  SYSTEMS/DATA ENGINEER - ANALYTICS- INFORMATION...
294   Corporate Analytics Manager (South of Milwaukee)
295                       Flight Control Data Engineer
296                                      Data Engineer
297               Sr Data Scientist - Machine Learning
298                                  Analytics Manager
299     Senior Data Scientist - Defense & Intelligence
300                   Scientist / Sr. Scientist - HPLC
301  Scientist / Engineer (Virtual Reality & Simula...
302  Senior Data Analytics Specialist (Data Scientist)
303                                Azure Data Engineer
304                                      Data Engineer
305   Lead Senior Data Engineer (Scala/Spark) - Remote
306       Machine Learning Engineer, Auction Mechanics
307                                Senior Data Analyst
308                Medical Lab Scientist- MLS- Evening
309               Senior Data / Bioinformatics Analyst
310                        Big Data Engineer/Developer
311                                       Data Analyst
312  Postdoctoral Scientist in Pharmaceutical & For...
313                                      Data Engineer
314       Senior Data Scientist/Researcher *clearable*
315  ASSOCIATE BUSINESS ANALYTICS CONSULTANT - FINANCE
316                                       Data Analyst
317                              Senior Data Scientist
318                                     Data Scientist
319                                AI/ML Data Engineer
320                                  Big Data Engineer
321                                     Data Scientist
322  Data Scientist – SQL Developer, Consultant - C...
323  Research Scientist - Computer Vision, Machine ...
324                                  Big Data Engineer
325     Image Data Scientist - Computational Pathology
326                              Senior Data Scientist
327                 Senior Programmer and Data Analyst
328                              Data Engineer- Hadoop
329                  Machine Learning Engineer, Senior
332                               Senior Data Engineer
333                        Data & Integration Engineer
334                              Data Engineer- Hadoop
335  Sr Data Scientist - Advanced Conversational Te...
336                                     Data Scientist
337          Data Scientist, Analytics-Remote Presence
338  Associate/Sr. Associate Scientist High Through...
339                                     Data Scientist
340                                       Data Analyst
341  Machine Learning Engineer, Natural Language Pr...
342                       Data Scientist - Chicago, IL
343                          Data Analytics Instructor
344                                 Sales Data Analyst
345                                      Data Engineer
346  Clinical Laboratory Technologist - Medical Lab...
347  Clinical Data Scientist Team Lead (PhD or Phar...
348                     Data Science (Privacy) Manager
349                                      Data Engineer
350                                     Data Scientist
351                Automotive Aftermarket Data Analyst
352                              Senior Data Scientist
353                                     Data Scientist
354                     Senior Data Scientist (MS2266)
355  Synthetic chemistry pharmaceutical research sc...
356                                     Data Scientist
357                     Senior Healthcare Data Analyst
358                         Machine Learning Scientist
359                                     Data Scientist
360                         Operational Data Scientist
361                                     Data Scientist
362                   Data Scientist with TS Clearance
363                                     Data Scientist

In [199]:
df_out.to_csv('salary_data_cleaned.csv',index = False)